Bookstore: initialize
Young-Gaius/bookstore-react-redux pull request #1
Opened 2023-08-25 19:08 UTC by Young-Gaius

This pull request adds the necessary components and functionality to meet the project requirements. Here's a summary of the changes:

Created a /components directory to store reusable components.
Installed React Router V6 and set up routing inside .
Added two routes: "/" and "/categories", each rendering a respective page component.
Implemented individual book components with the remove button.
Created a book component to render individual books.
Added an aadBook component to create new books.
Updated the design of the bookstore to replace the category input with an author input.

2023-08-25 19:55 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @Young-Gaius, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 19:55 UTC, Qoosim commented on src/components/Book.js
> +    <Books />
- [ ] Great job for initializing your component. Hhowever, there's little stuff to get correctly here. This BooksPage should render list of books using your Books component. It requires props to be passed and use that props in the Books component to render the value of the props on the browser. It should look something similar to this :point_down: 

```
const BooksPage = () => (
   <>
      <Books title="Book One" author="Author One" />
      <AddBook />
    </>  
)
```

2023-08-25 19:55 UTC, Qoosim commented on src/components/Books.js
> +        </h3>
- [ ] What is needed here is to use the props and the values would be displayed. Something like this :point_down: 

```
   <h3>{title}</h3>
     
   <h3>Byt: {author}</h3>
```

2023-08-26 15:59 UTC, divinecharlotte approved these changes
# Hello @Young-Gaius       😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯


- Good implementation of the required changes👍 
- well-organized file structure✔ 👍
 




## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-29 14:41 UTC, merged